extern "C" {
#include "hello.h"
}

//The compiler wants to know the symbol of each signature.
//We need to put the extern "C" above because we need to tell the linker that the symbol
//Of the function hello_from_c has been generated by a c compiler.
int main() {
  hello_from_c();
  return 0;
}
